apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: argo-events
  labels:
    component: nats
spec:
  selector:
    component: nats
  type: NodePort
  ports:
  - name: client
    nodePort: 30080
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: argo-events
  labels:
    component: nats
spec:
  serviceName: nats
  replicas: 1
  selector:
    matchLabels:
      component: nats
  template:
    metadata:
      labels:
        component: nats
    spec:
      containers:
      - name: nats
        args:
        - -V
        image: nats:latest
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
